logging:
    level: INFO

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/geolocation
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: none
    show_sql: true
